builders:
  entry_point_builder:
    import: "package:pocket_functions/builder.dart"
    builder_factories: ["entryPointBuilder"]
    build_extensions: { ".dart": [".entrypoint.g.dart"] }
    auto_apply: dependents
    build_to: source
    runs_before: []
