name: dart_function
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  pocket_functions:
    path: /Users/gazer/dev/pocketfunctions/dart/pocket_functions
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.3.3
  pocket_functions:
    path: /Users/gazer/dev/pocketfunctions/dart/pocket_functions
  lints: ^4.0.0
  test: ^1.24.0

pocket_functions:
  path: /saraza
