name: pocketbase_example
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.2

# Add regular dependencies here.
dependencies:
  pocketbase: ^0.18.1
  pocket_functions:
    git: https://github.com/Gazer/exp-pocketfunct-dart

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  pocket_functions:
    git: https://github.com/Gazer/exp-pocketfunct-dart
  build_runner: ^2.3.3

pocket_functions:
  path: /items
